docs-conceptual/partnercenterps-1.5/secure-app-model.md

This pull request corrects an issues with the Create-AzureADApplication.ps1 script

Minor update to the script to create an Azure AD application

---

docs-conceptual/partnercenterps-1.5/secure-app-model.md
partnercenterps-1.5/PartnerCenter/Connect-PartnerCenter.md
partnercenterps-1.5/PartnerCenter/New-PartnerAccessToken.md

Updates to the Create-AzureADApplication.ps1 script

Minor script updates

---

partnercenterps-1.5/PartnerCenter/Connect-PartnerCenter.md
partnercenterps-1.5/PartnerCenter/New-PartnerAccessToken.md

Through this pull request the updates are being made to reflect the latest release.

Updates to reflect the latest release

---

partnercenterps-1.5/PartnerCenter/Add-PartnerCustomerCartLineItem.md
partnercenterps-1.5/PartnerCenter/Connect-PartnerCenter.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomer.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerEntitlement.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerOrder.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerSubscription.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerSubscriptionAddOn.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerUser.md
partnercenterps-1.5/PartnerCenter/Get-PartnerOfferAddon.md
partnercenterps-1.5/PartnerCenter/Get-PartnerProduct.md
partnercenterps-1.5/PartnerCenter/Get-PartnerProductAvailability.md
partnercenterps-1.5/PartnerCenter/Get-PartnerProductSKU.md
partnercenterps-1.5/PartnerCenter/Get-PartnerServiceRequest.md
partnercenterps-1.5/PartnerCenter/New-PartnerAccessToken.md
partnercenterps-1.5/PartnerCenter/New-PartnerCustomerDeviceBatch.md
partnercenterps-1.5/PartnerCenter/New-PartnerCustomerOrder.md
partnercenterps-1.5/PartnerCenter/New-PartnerServiceRequest.md
partnercenterps-1.5/PartnerCenter/Remove-PartnerCustomerUser.md
partnercenterps-1.5/PartnerCenter/Restore-PartnerCustomerUser.md
partnercenterps-1.5/PartnerCenter/Set-PartnerCustomer.md
partnercenterps-1.5/PartnerCenter/Set-PartnerCustomerSubscription.md
partnercenterps-1.5/PartnerCenter/Set-PartnerCustomerUser.md

Through this pull request minor updates are being made to the documentation

Minor updates ot the documentation

---

docfx.json
docs-conceptual/partnercenterps-1.5/install.md
docs-conceptual/partnercenterps-1.5/overview.md
docs-conceptual/partnercenterps-1.5/secure-app-model.md
partnercenterps-1.5/PartnerCenter/Connect-PartnerCenter.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCountryValidation.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerEntitlement.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerOrder.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerOrderLineItemActivationLink.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerOrderProvisioningStatus.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerQualification.md
partnercenterps-1.5/PartnerCenter/Get-PartnerInvoiceLineItem.md
partnercenterps-1.5/PartnerCenter/Get-PartnerInvoiceTaxReceiptStatement.md
partnercenterps-1.5/PartnerCenter/Get-PartnerServiceIncident.md
partnercenterps-1.5/PartnerCenter/Get-PartnerValidationCode.md
partnercenterps-1.5/PartnerCenter/New-PartnerAccessToken.md
partnercenterps-1.5/PartnerCenter/New-PartnerCustomer.md
partnercenterps-1.5/PartnerCenter/New-PartnerCustomerAgreement.md
partnercenterps-1.5/PartnerCenter/New-PartnerCustomerApplicationConsent.md
partnercenterps-1.5/PartnerCenter/New-PartnerServiceRequest.md
partnercenterps-1.5/PartnerCenter/PartnerCenter.md
partnercenterps-1.5/PartnerCenter/Set-PartnerBillingProfile.md
partnercenterps-1.5/PartnerCenter/Set-PartnerCustomer.md
partnercenterps-1.5/PartnerCenter/Set-PartnerCustomerQualification.md
partnercenterps-1.5/PartnerCenter/Set-PartnerCustomerSubscription.md
partnercenterps-1.5/PartnerCenter/Set-PartnerCustomerUser.md
partnercenterps-1.5/PartnerCenter/Set-PartnerLegalProfile.md
partnercenterps-1.5/PartnerCenter/Set-PartnerOrganizationProfile.md

Through this pull request the changes for the upcoming March release are being made

Updates for the March release

---

docfx.json
docs-conceptual/partnercenterps-1.5/install.md
docs-conceptual/partnercenterps-1.5/overview.md
docs-conceptual/partnercenterps-1.5/secure-app-model.md
partnercenterps-1.5/PartnerCenter/Connect-PartnerCenter.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCountryValidation.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerEntitlement.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerOrder.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerOrderLineItemActivationLink.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerOrderProvisioningStatus.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerQualification.md
partnercenterps-1.5/PartnerCenter/Get-PartnerInvoiceLineItem.md
partnercenterps-1.5/PartnerCenter/Get-PartnerInvoiceTaxReceiptStatement.md
partnercenterps-1.5/PartnerCenter/Get-PartnerServiceIncident.md
partnercenterps-1.5/PartnerCenter/Get-PartnerValidationCode.md
partnercenterps-1.5/PartnerCenter/New-PartnerAccessToken.md
partnercenterps-1.5/PartnerCenter/New-PartnerCustomer.md
partnercenterps-1.5/PartnerCenter/New-PartnerCustomerAgreement.md
partnercenterps-1.5/PartnerCenter/New-PartnerCustomerApplicationConsent.md
partnercenterps-1.5/PartnerCenter/New-PartnerServiceRequest.md
partnercenterps-1.5/PartnerCenter/PartnerCenter.md
partnercenterps-1.5/PartnerCenter/Set-PartnerBillingProfile.md
partnercenterps-1.5/PartnerCenter/Set-PartnerCustomer.md
partnercenterps-1.5/PartnerCenter/Set-PartnerCustomerQualification.md
partnercenterps-1.5/PartnerCenter/Set-PartnerCustomerSubscription.md
partnercenterps-1.5/PartnerCenter/Set-PartnerCustomerUser.md
partnercenterps-1.5/PartnerCenter/Set-PartnerLegalProfile.md
partnercenterps-1.5/PartnerCenter/Set-PartnerOrganizationProfile.md

* Updates for the March release

Updates for the March release (#34)

---

breadcrumb/toc.yml
docfx.json
docs-conceptual/partnercenterps-1.5/multi-factor-auth.md
docs-conceptual/partnercenterps-1.5/overview.md
docs-conceptual/partnercenterps-1.5/toc.yml

Through this pull request more information regarding multi-factor authentication is being added.

MFA Update

---

breadcrumb/toc.yml
docfx.json
docs-conceptual/partnercenterps-1.5/multi-factor-auth.md
docs-conceptual/partnercenterps-1.5/overview.md
docs-conceptual/partnercenterps-1.5/toc.yml

Through this pull request the first round of multi-factor authentication documentation is being merged into the public documentation.

MFA Update (#37)

---

breadcrumb/toc.yml
docfx.json
docs-conceptual/partnercenterps-1.5/multi-factor-auth.md
docs-conceptual/partnercenterps-1.5/overview.md
docs-conceptual/partnercenterps-1.5/secure-app-model.md
docs-conceptual/partnercenterps-1.5/toc.yml

Through this pull request updates from the live branch are being merged into the master branch

Merging updates from live to master

---

docs-conceptual/partnercenterps-1.5/multi-factor-auth.md
docs-conceptual/partnercenterps-1.5/secure-app-model.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerUser.md
partnercenterps-1.5/PartnerCenter/New-PartnerCustomerAgreement.md
partnercenterps-1.5/PartnerCenter/New-PartnerCustomerDeviceBatch.md
partnercenterps-1.5/PartnerCenter/New-PartnerCustomerUser.md
partnercenterps-1.5/PartnerCenter/Set-PartnerCustomerUser.md

Through this pull request the documentation is being updated to reflect the latest release

Release update

---

docs-conceptual/partnercenterps-1.5/secure-app-model.md

Added -TenantId to examples using `New-PartnerAccessToken` cmdlets

Secure Application Model updates

---

partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerSubscriptionUtilization.md
partnercenterps-1.5/PartnerCenter/Get-PartnerCustomerUserRole.md
partnercenterps-1.5/PartnerCenter/Get-PartnerRole.md
partnercenterps-1.5/PartnerCenter/Get-PartnerRoleMember.md
partnercenterps-1.5/PartnerCenter/PartnerCenter.md
partnercenterps-1.5/PartnerCenter/Set-PartnerCustomerSubscription.md

Through this pull request the documentation is being updated to reflect the latest release

Updating the command documentation to reflect the latest release

---

docs-conceptual/partnercenterps-1.5/install.md
docs-conceptual/partnercenterps-1.5/toc.yml

Through this pull request the installation documentation is being updated

Updating the installation documentation

---

docs-conceptual/partnercenterps-1.5/install.md
docs-conceptual/partnercenterps-1.5/toc.yml

Through this pull request the installation documentation is being updated

Updating the installation documentation (#51)

---

.openpublishing.redirection.json
docfx.json
docs-conceptual/partnercenterps-2.0/release-notes.md
partnercenterps-2.0/PartnerCenter/Connect-PartnerCenter.md
partnercenterps-2.0/PartnerCenter/New-PartnerAccessToken.md

Through this pull request minor changes are being made to reflect the latest release

Updating the documentation to reflect the latest release

---

docs-conceptual/partnercenterps-2.0/overview.md
docs-conceptual/partnercenterps-2.0/release-notes.md
docs-conceptual/partnercenterps-2.0/test-partner-security-requirements.md
docs-conceptual/partnercenterps-2.0/toc.yml
partnercenterps-2.0/PartnerCenter/Connect-PartnerCenter.md
partnercenterps-2.0/PartnerCenter/Get-PartnerAgreementDetail.md
partnercenterps-2.0/PartnerCenter/Get-PartnerAgreementDocument.md
partnercenterps-2.0/PartnerCenter/New-PartnerAccessToken.md
partnercenterps-2.0/PartnerCenter/New-PartnerCustomerDeviceBatch.md
partnercenterps-2.0/PartnerCenter/PartnerCenter.md
partnercenterps-2.0/PartnerCenter/Remove-PartnerCustomerUser.md
partnercenterps-2.0/PartnerCenter/Test-PartnerSecurityRequirement.md

Through this pull request updates are being made to reflect the latest changes

Updating the documentation

---

docfx.json
docs-conceptual/partnercenterps-2.0/breaking-changes.md
docs-conceptual/partnercenterps-2.0/release-notes.md
docs-conceptual/partnercenterps-2.0/test-partner-security-requirements.md
partnercenterps-2.0/PartnerCenter/Add-PartnerCustomerCartLineItem.md
partnercenterps-2.0/PartnerCenter/Connect-PartnerCenter.md
partnercenterps-2.0/PartnerCenter/Get-PartnerCustomerAzurePlanEntitlement.md
partnercenterps-2.0/PartnerCenter/Get-PartnerCustomerSubscriptionMeterUsage.md
partnercenterps-2.0/PartnerCenter/Get-PartnerCustomerSubscriptionResourceUsage.md
partnercenterps-2.0/PartnerCenter/Get-PartnerCustomerSubscriptionUsage.md
partnercenterps-2.0/PartnerCenter/Get-PartnerCustomerUsageRecord.md
partnercenterps-2.0/PartnerCenter/Get-PartnerProductUpgradeEligibility.md
partnercenterps-2.0/PartnerCenter/Get-PartnerProductUpgradeStatus.md
partnercenterps-2.0/PartnerCenter/New-PartnerAccessToken.md
partnercenterps-2.0/PartnerCenter/New-PartnerProductUpgrade.md
partnercenterps-2.0/PartnerCenter/PartnerCenter.md

Through this pull request the changes related to the upcoming preview release are being made.

Preview release update

---

docfx.json
docs-conceptual/partnercenterps-2.0/multi-factor-auth.md

Through this pull request the multi-factor authentication documentation is being updated

Updating the MFA documentation

---

partnercenterps-2.0/PartnerCenter/Get-PartnerProductUpgradeStatus.md

Through this pull request the documentation for the Get-PartnerProductUpgradeStatus is being updated

Updating the command documentation

---

partnercenterps-2.0/PartnerCenter/Get-PartnerUserSignInActivity.md

Through this pull request the partner user sign-in activity documentation is being updated

Updating the partner user sign-in activity command

---

docfx.json
docs-conceptual/partnercenterps-2.0/release-notes.md
partnercenterps-2.0/PartnerCenter/Get-PartnerAzureBillingAccount.md
partnercenterps-2.0/PartnerCenter/Get-PartnerAzureBillingProfile.md
partnercenterps-2.0/PartnerCenter/Get-PartnerCountryValidation.md
partnercenterps-2.0/PartnerCenter/Get-PartnerUser.md
partnercenterps-2.0/PartnerCenter/New-PartnerAzureSubscription.md
partnercenterps-2.0/PartnerCenter/PartnerCenter.md

Through this pull request changes are being made to reflect the latest release

Updating to reflect the latest release

---

docs-conceptual/partnercenterps-3.0/multi-factor-auth.md

Through this pull request the Exchange Online sample is being updated

Updating the Exchange Online sample

---

docs-conceptual/partnercenterps-3.0/release-notes.md

Through this pull request the release notes are being updated

Updating the release notes

---

docfx.json
docs-conceptual/partnercenterps-3.0/breaking-changes.md
docs-conceptual/partnercenterps-3.0/release-notes.md
partnercenterps-3.0/PartnerCenter/Connect-PartnerCenter.md
partnercenterps-3.0/PartnerCenter/Enable-PartnerAzureSubscription.md
partnercenterps-3.0/PartnerCenter/Get-PartnerUserSignInActivity.md
partnercenterps-3.0/PartnerCenter/New-PartnerAzureSubscription.md
partnercenterps-3.0/PartnerCenter/PartnerCenter.md
partnercenterps-3.0/PartnerCenter/Suspend-PartnerAzureSubscription.md

Through this pull request the documentation is being updated to includes changes from the latest release

Updating the documentation to include changes for the latest release

---

docfx.json
docs-conceptual/partnercenterps-1.5/install.md
docs-conceptual/partnercenterps-2.0/install.md
docs-conceptual/partnercenterps-3.0/install.md

Through this pull request a link is being updated

Updating a link

---

docfx.json
docs-conceptual/partnercenterps-3.0/multi-factor-auth.md
docs-conceptual/partnercenterps-3.0/release-notes.md
partnercenterps-3.0/PartnerCenter/Get-PartnerCustomerUser.md
partnercenterps-3.0/PartnerCenter/Get-PartnerInvoiceLineItem.md
partnercenterps-3.0/PartnerCenter/New-PartnerAccessToken.md

Through this pull request updates are being made for the next release

Updates to prepare for the next update

---

docs-conceptual/partnercenterps-2.0/multi-factor-auth.md

Does not work without and fill and not use make no sense

Use the $credential variable

---

docs-conceptual/partnercenterps-2.0/multi-factor-auth.md

Through this pull request the changes made to the live branch are being merged with the master branch

Merging changes

---

docfx.json

Making the ms.service value consistent with the rest of partner center.

Adjusting msservice metadata

---

docs-conceptual/partnercenterps-3.0/multi-factor-auth.md

These changes reflect the working solution obtained with the assistance of the Technical Presales & Deployment Services | CSS Partner Enablement team.

Correct doc for Exchange Online MFA PWSH connection

---

docs-conceptual/partnercenterps-3.0/multi-factor-auth.md

Through this pull request the following changes are being made
- Adding clarification to the Exchange Online samples
- Updating the Az module samples

Updating the latest MFA guidance

---

docfx.json

Turning off issues on Docs for now. We don't have a clear business process to triage. Yammer's feedback channel is preferred according to my discussion with Vijay Vala.

2020-07-20 Publish master to live

---

docs-conceptual/partnercenterps-2.0/release-notes.md
docs-conceptual/partnercenterps-3.0/release-notes.md

Through this pull request broken links are being fixed

Updating links

---

.openpublishing.publish.config.json
.openpublishing.redirection.json
breadcrumb/toc.yml
docs-conceptual/index.md

[AB#294609](https://dev.azure.com/ceapex/Engineering/_workitems/edit/294609)
This Pull Request is for docfxv3 migration, after the Pull Request merged, the repository will be built with docfxv3 instead of docfxv2.

Update config to enable docfx v3

---

docs-conceptual/partnercenterps-3.0/multi-factor-auth.md

Through this pull request the title for the MFA documentation is being updated.

Adjust title 

---

.openpublishing.publish.config.json
breadcrumb/toc.yml
docfx.json

This is for the request: https://dev.azure.com/msft-skilling/Content/_workitems/edit/295068

archive the repo
